package:
  version: '1.4.0'
  name: "datasail"

source:
  path: ..

build:
  entry_points:
    - datasail = datasail.sail:sail
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  # script: python setup.py install

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python>=3.10,<3.14.0
    - numpy
    - pandas
    - matplotlib
    - pyscipopt
    - scip<=9.1
    - scikit-learn
    - cvxpy
    - rdkit
    - pyyaml
    - cvxopt
    - h5py
    - pyarrow
    - tqdm
    - importlib_resources

test:
  requires:
    - pytest
    - pytest-cov
    - pytest-cases
  imports:
    - datasail
  commands:
    - datasail --help

about:
  home: https://github.com/kalininalab/DataSAIL
  license: MIT
  license_file: LICENSE
  summary: DataSAIL is a tool to split datasets while reducing information leakage.
