name: Publish DataSAIL

on:
  release:
    types: [published]
  workflow_dispatch:
    
jobs:
  publish:
    strategy:
      matrix:
        python-version:
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
        datasail-versions:
          - 'full'
          - 'lite'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4

    - name: Setup Mamba
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        miniforge-version: latest
        activate-environment: MPP
        use-mamba: true

    - name: Install environment
      shell: bash -l {0}
      run: |
        conda install -y anaconda-client conda-build git

    - name: Build DataSAIL for linux-64
      if: matrix.datasail-versions == 'full'
      shell: bash -l {0}
      run: |
        conda-build -q -c conda-forge -c bioconda --output-folder . --no-test --append-file base_recipe.yaml recipe

    - name: Convert DataSAIL to osx-64
      if: matrix.datasail-versions == 'full'
      shell: bash -l {0}
      run: |
        conda convert -p osx-64 linux-64/*.conda

    - name: Publish DataSAIL to Conda
      if: matrix.datasail-versions == 'full'
      env:
        ANACONDA_TOKEN: ${{ secrets.DATASAIL_ANACONDA_TOKEN }}
      shell: bash -l {0}
      run: |
        anaconda -t "$ANACONDA_TOKEN" upload linux-64/*.conda
        anaconda -t "$ANACONDA_TOKEN" upload osx-64/*.conda

    - name: Build DataSAIL for linux-64
      if: matrix.datasail-versions == 'lite'
      shell: bash -l {0}
      run: |
        conda-build -q -c conda-forge -c bioconda --output-folder . --no-test --append-file base_recipe.yaml recipe_lite

    - name: Convert DataSAIL to osx-64, osx-arm64, win-64
      if: matrix.datasail-versions == 'lite'
      shell: bash -l {0}
      run: |
        conda convert -p osx-64 linux-64/*.conda
        conda convert -p osx-arm64 linux-64/*.conda
        conda convert -p win-64 linux-64/*.conda

    - name: Publish DataSAIL-lite to Conda
      if: matrix.datasail-versions == 'lite'
      env:
        ANACONDA_TOKEN: ${{ secrets.DATASAIL_ANACONDA_TOKEN }}
      shell: bash -l {0}
      run: |
        anaconda -t "$ANACONDA_TOKEN" upload linux-64/*.conda
        anaconda -t "$ANACONDA_TOKEN" upload osx-64/*.conda
        anaconda -t "$ANACONDA_TOKEN" upload osx-arm64/*.conda
        anaconda -t "$ANACONDA_TOKEN" upload win-64/*.conda
