name: Publish DataSAIL-lite

on:
  release:
    types: [published]
  workflow_dispatch:
    
jobs:
  publish:
    strategy:
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4

    - name: Setup Mamba
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        miniforge-variant: Mambaforge
        miniforge-version: latest
        activate-environment: MPP
        use-mamba: true

    - name: Install environment
      shell: bash -l {0}
      run: |
        conda install -y anaconda-client conda-build git

    - name: Build DataSAIL for linux-64
      shell: bash -l {0}
      run: |
        conda-build -q --variants -c conda-forge -c bioconda --output-folder . --no-test recipe_lite

    - name: Convert DataSAIL to osx-64, osx-arm64, win-64
      shell: bash -l {0}
      run: |
        conda convert -p osx-64 linux-64/*.tar.bz2
        conda convert -p osx-arm64 linux-64/*.tar.bz2
        conda convert -p win-64 linux-64/*.tar.bz2

    - name: Publish DataSAIL-lite to Conda
      env:
        ANACONDA_TOKEN: ${{ secrets.DATASAIL_ANACONDA_TOKEN }}
      shell: bash -l {0}
      run: |
        anaconda -t "$ANACONDA_TOKEN" upload linux-64/*.tar.bz2
        anaconda -t "$ANACONDA_TOKEN" upload osx-64/*.tar.bz2
        anaconda -t "$ANACONDA_TOKEN" upload osx-arm64/*.tar.bz2
        anaconda -t "$ANACONDA_TOKEN" upload win-64/*.tar.bz2
