name: publish_conda

on:
  # release:
  #   types: [published]
  workflow_dispatch:
    
jobs:
  publish:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1
    - name: publish-to-conda
      uses: Old-Shatterhand/publish-conda-multichannel-action@v0.0.9
      with:
        AnacondaToken: ${{ secrets.DATASAIL_ANACONDA_TOKEN }}
        Versions: "3.11"
        Folder: "recipe"
