# This is a basic workflow to help you get started with Actions

name: Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:  # make is manually start-able

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Mamba
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: '3.10'
          miniforge-version: latest
          activate-environment: MPP
          use-mamba: true
          
      - name: Install environment
        shell: bash -l {0}
        run: |
          mamba install -c conda-forge -c bioconda -y numpy"<2" pandas networkx matplotlib pytest setuptools pyscipopt==5.2.1 foldseek mmseqs2 cd-hit mash tmalign diamond cvxpy==1.5.3 pytest-cov rdkit">=2023.09.1" pytest-cases scikit-learn pyyaml h5py pyarrow tqdm
          pip install grakel
        
      - name: Run tests
        shell: bash -l {0}
        run: |
          cd tests
          pytest -m "not todo and not issue" --cov=../datasail/ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          files: coverage.xml
