# This is a basic workflow to help you get started with Actions

name: Testing All Python Versions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
      - dev
      - main_numpy
  pull_request:
    branches:
      - main
      - dev
      - main_numpy
  workflow_dispatch:  # make is manually start-able

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.13'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v6
      
      - name: Setup Mamba
        uses: conda-incubator/setup-miniconda@v4
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge
          channel-priority: true
          activate-environment: MPP
          use-mamba: true

      - name: Install environment
        shell: bash -l {0}
        run: |
          pip install numpy pandas networkx matplotlib pyscipopt cvxpy rdkit">=2023.09.1" scikit-learn pyyaml h5py pyarrow tqdm importlib_resources setuptools pytest"==9.0.3" pytest-cov pytest-cases
          mamba install -c conda-forge -c bioconda --override-channels -y foldseek mmseqs2 cd-hit mash tmalign diamond

      - name: Run tests
        shell: bash -l {0}
        run: |
          cd tests
          pytest -m "not todo and not issue"
